#!/bin/bash
echo "========================================"
echo "  INSTALANDO DEPENDENCIAS"
echo "========================================"
echo ""
echo "Esto puede tardar unos minutos..."
echo ""
npm install
echo ""
echo "========================================"
echo "  INSTALACION COMPLETADA"
echo "========================================"
echo ""
echo "Ahora podés ejecutar: ./START.sh"
echo ""
